/**
 * Variables provided to API operations.
 *
 * These variables are automatically generated and provided by the Turbo Firestore system
 * when performing create, update, or upsert operations. They ensure consistent
 * handling of IDs and timestamps across all operations.
 *
 * @example
 * ```typescript
 * const createUser: CreateDocDef<User> = (vars) => ({
 *   id: vars.id,
 *   name: 'New User',
 *   createdAt: vars.now,
 *   updatedAt: vars.now,
 * });
 * ```
 */
export interface TurboApiVars {
  /**
   * Auto-generated document ID.
   *
   * This ID is automatically generated by Firestore when creating a new document.
   * It is guaranteed to be unique within the collection.
   */
  readonly id: string;

  /**
   * Current timestamp.
   *
   * This represents the exact moment when the operation is being performed.
   * Useful for setting createdAt, updatedAt, or other timestamp fields.
   */
  readonly now: Date;
}
